Improve ocijail startup procedure
- better errors handling
- waiting for jail creation - it may take a while on slow hardware
- properly set nice, move setup_jail_nice into procedure
- run setup_jail_vnet not under 'set -e'

busybox success start:
```shell
host# cbsd jcreate jname=busybox from=docker.io/library/busybox platform=linux
...
Creating busybox complete: Enjoy!
cbsd done in 3 seconds
emulator_flags: ocijail
exec_start: sleep 1000

host# cbsd jstart busybox
cbsd: waiting for busybox JID status=created: 1/6 ...
Startup logs: /jails/ftmp/jstart.busybox.out /jails/ftmp/jstart.busybox.err
cbsd done in 1 seconds
```

Failure example - cannot create jail:
```shell
host# cbsd jstart busybox
cbsd: waiting for busybox JID status=: 6/6 ...
Error: OCI jail busybox failed to create
2026-02-12T23:47:11000231735Z: error calling jail_set: IPv4 addresses clash: Address already in use
```